#include <stdio.h>

/*
This is a simple Hello world in C. It will be compiled using gcc (gcc .\E000_Hello-World.c -g -o ..\CompiledWithSymbols\E000_Hello-World.exe for the symbol version).
The objective with this exercise is to familiarize with the decompilation tool, notice there is code that is generated by the compiler, and in the stripped compilation, to find main.
[Tip: Your decompilation tool may have a search string feature, for now it will be helpful to find main]


"The journey of a thousand miles begins with one step" -Lao Tzu
*/

int main(int argc, char * argvar[]) {
    printf("Hello, World!\n");
    return 0;
}